template: |
  # v$RESOLVED_VERSION

  ## How to install

  See [here](https://github.com/juho05/crossonic#installation) for installation instructions.

  ## What's Changed

  ### New Features

  - TODO

  ### Bug Fixes

  - TODO

  **Full Changelog:** [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
