targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/ui/**_page.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/routing/router.dart
      json_serializable:
        options:
          create_to_json: true
          checked: true
          include_if_null: false
      drift_dev:
        options:
          store_date_time_values_as_text: true
          databases:
            db: lib/data/services/database/database.dart
