// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [keyValue, scrobble];
  late final Shape0 keyValue = Shape0(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 scrobble = Shape1(
    source: i0.VersionedTable(
      entityName: 'scrobble',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(song_id, start_time)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get songId =>
      columnsByName['song_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get listenDurationMs =>
      columnsByName['listen_duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get songDurationMs =>
      columnsByName['song_duration_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'song_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_3(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'start_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'listen_duration_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'song_duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    keyValue,
    scrobble,
    playlist,
    playlistSong,
  ];
  late final Shape0 keyValue = Shape0(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 scrobble = Shape1(
    source: i0.VersionedTable(
      entityName: 'scrobble',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(song_id, start_time)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 playlist = Shape2(
    source: i0.VersionedTable(
      entityName: 'playlist',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 playlistSong = Shape3(
    source: i0.VersionedTable(
      entityName: 'playlist_song',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_2, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get comment =>
      columnsByName['comment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get songCount =>
      columnsByName['song_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get created =>
      columnsByName['created']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get changed =>
      columnsByName['changed']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get coverArt =>
      columnsByName['cover_art']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get download =>
      columnsByName['download']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'comment',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'song_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<DateTime> _column_11(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'created',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_12(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'changed',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_art',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_14(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'download',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("download" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get playlistId =>
      columnsByName['playlist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get index =>
      columnsByName['index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get songId =>
      columnsByName['song_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get childModelJson =>
      columnsByName['child_model_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'playlist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES playlist (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'child_model_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    keyValue,
    scrobble,
    playlist,
    playlistSong,
    downloadTask,
  ];
  late final Shape0 keyValue = Shape0(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 scrobble = Shape1(
    source: i0.VersionedTable(
      entityName: 'scrobble',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(song_id, start_time)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 playlist = Shape2(
    source: i0.VersionedTable(
      entityName: 'playlist',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 playlistSong = Shape3(
    source: i0.VersionedTable(
      entityName: 'playlist_song',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_2, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 downloadTask = Shape4(
    source: i0.VersionedTable(
      entityName: 'download_task',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(task_id, type)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get object =>
      columnsByName['object']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get group =>
      columnsByName['group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'object',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_24(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'updated',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    keyValue,
    scrobble,
    playlist,
    playlistSong,
    downloadTask,
    favorites,
  ];
  late final Shape0 keyValue = Shape0(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 scrobble = Shape1(
    source: i0.VersionedTable(
      entityName: 'scrobble',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(song_id, start_time)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 playlist = Shape2(
    source: i0.VersionedTable(
      entityName: 'playlist',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 playlistSong = Shape3(
    source: i0.VersionedTable(
      entityName: 'playlist_song',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_2, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 downloadTask = Shape4(
    source: i0.VersionedTable(
      entityName: 'download_task',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(task_id, type)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 favorites = Shape5(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id, type)'],
      columns: [_column_6, _column_25, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get starred =>
      columnsByName['starred']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<DateTime> _column_25(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'starred',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    keyValue,
    scrobble,
    playlist,
    playlistSong,
    downloadTask,
    favorites,
    logMessage,
  ];
  late final Shape0 keyValue = Shape0(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 scrobble = Shape1(
    source: i0.VersionedTable(
      entityName: 'scrobble',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(song_id, start_time)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 playlist = Shape2(
    source: i0.VersionedTable(
      entityName: 'playlist',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 playlistSong = Shape3(
    source: i0.VersionedTable(
      entityName: 'playlist_song',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_15, _column_16, _column_17, _column_2, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 downloadTask = Shape4(
    source: i0.VersionedTable(
      entityName: 'download_task',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(task_id, type)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 favorites = Shape5(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id, type)'],
      columns: [_column_6, _column_25, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 logMessage = Shape6(
    source: i0.VersionedTable(
      entityName: 'log_message',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get sessionStartTime =>
      columnsByName['session_start_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get time =>
      columnsByName['time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get level =>
      columnsByName['level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tag =>
      columnsByName['tag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get message =>
      columnsByName['message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stackTrace =>
      columnsByName['stack_trace']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exception =>
      columnsByName['exception']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<DateTime> _column_26(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'session_start_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_27(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'time',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'message',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stack_trace',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exception',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    keyValue,
    scrobble,
    playlist,
    playlistSong,
    downloadTask,
    favorites,
    logMessage,
    coverCache,
  ];
  late final Shape0 keyValue = Shape0(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_0, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 scrobble = Shape1(
    source: i0.VersionedTable(
      entityName: 'scrobble',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(song_id, start_time)'],
      columns: [_column_2, _column_3, _column_4, _column_5],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 playlist = Shape2(
    source: i0.VersionedTable(
      entityName: 'playlist',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 playlistSong = Shape7(
    source: i0.VersionedTable(
      entityName: 'playlist_song',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_16,
        _column_17,
        _column_2,
        _column_33,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 downloadTask = Shape4(
    source: i0.VersionedTable(
      entityName: 'download_task',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(task_id, type)'],
      columns: [
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 favorites = Shape5(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id, type)'],
      columns: [_column_6, _column_25, _column_20],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 logMessage = Shape6(
    source: i0.VersionedTable(
      entityName: 'log_message',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_15,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 coverCache = Shape8(
    source: i0.VersionedTable(
      entityName: 'cover_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(cover_id, size)'],
      columns: [
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get playlistId =>
      columnsByName['playlist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get index =>
      columnsByName['index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get songId =>
      columnsByName['song_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverId =>
      columnsByName['cover_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get childModelJson =>
      columnsByName['child_model_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get coverId =>
      columnsByName['cover_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get size =>
      columnsByName['size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get fileFullyWritten =>
      columnsByName['file_fully_written']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get downloadTime =>
      columnsByName['download_time']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get validTill =>
      columnsByName['valid_till']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get fileSizeKB =>
      columnsByName['file_size_k_b']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<bool> _column_36(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'file_fully_written',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("file_fully_written" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<DateTime> _column_37(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'download_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<DateTime> _column_38(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'valid_till',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_size_k_b',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    keyValue,
    scrobble,
    playlist,
    song,
    playlistSong,
    downloadTask,
    favorites,
    logMessage,
    coverCache,
  ];
  late final Shape0 keyValue = Shape0(
    source: i0.VersionedTable(
      entityName: 'key_value',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 scrobble = Shape9(
    source: i0.VersionedTable(
      entityName: 'scrobble',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(song_id, start_time)'],
      columns: [_column_42, _column_43, _column_44, _column_45],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 playlist = Shape10(
    source: i0.VersionedTable(
      entityName: 'playlist',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 song = Shape11(
    source: i0.VersionedTable(
      entityName: 'song',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_46,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_69,
        _column_70,
        _column_71,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 playlistSong = Shape12(
    source: i0.VersionedTable(
      entityName: 'playlist_song',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_72, _column_73, _column_74, _column_75],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 downloadTask = Shape13(
    source: i0.VersionedTable(
      entityName: 'download_task',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(task_id, type)'],
      columns: [
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_71,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 favorites = Shape14(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id, type)'],
      columns: [_column_46, _column_81, _column_77],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 logMessage = Shape15(
    source: i0.VersionedTable(
      entityName: 'log_message',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_72,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 coverCache = Shape16(
    source: i0.VersionedTable(
      entityName: 'cover_cache',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(cover_id, size)'],
      columns: [
        _column_55,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get songId =>
      columnsByName['song_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startTime =>
      columnsByName['start_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get listenDurationMs =>
      columnsByName['listen_duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get songDurationMs =>
      columnsByName['song_duration_ms']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'song_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'start_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'listen_duration_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'song_duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get comment =>
      columnsByName['comment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get songCount =>
      columnsByName['song_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get created =>
      columnsByName['created']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get changed =>
      columnsByName['changed']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverArt =>
      columnsByName['cover_art']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get download =>
      columnsByName['download']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'comment',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'song_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'changed',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_art',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'download',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (download IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get coverId =>
      columnsByName['cover_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayArtist =>
      columnsByName['display_artist']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get artists =>
      columnsByName['artists']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get albumId =>
      columnsByName['album_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get albumName =>
      columnsByName['album_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genres =>
      columnsByName['genres']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get bpm =>
      columnsByName['bpm']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trackNr =>
      columnsByName['track_nr']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get discNr =>
      columnsByName['disc_nr']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get trackGain =>
      columnsByName['track_gain']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get albumGain =>
      columnsByName['album_gain']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get fallbackGain =>
      columnsByName['fallback_gain']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get originalDate =>
      columnsByName['original_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get releaseDate =>
      columnsByName['release_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cover_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_artist',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'artists',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'album_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'album_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'genres',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_62(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bpm',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'track_nr',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'disc_nr',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_66(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'track_gain',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_67(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'album_gain',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_68(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'fallback_gain',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'original_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'release_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get playlistId =>
      columnsByName['playlist_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get index =>
      columnsByName['index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get songId =>
      columnsByName['song_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_72(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'playlist_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES playlist(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_74(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'song_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES song(id)',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get taskId =>
      columnsByName['task_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get object =>
      columnsByName['object']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get group =>
      columnsByName['group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updated =>
      columnsByName['updated']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_76(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_78(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'object',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_79(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get starred =>
      columnsByName['starred']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'starred',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sessionStartTime =>
      columnsByName['session_start_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get time =>
      columnsByName['time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get level =>
      columnsByName['level']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get tag =>
      columnsByName['tag']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get message =>
      columnsByName['message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stackTrace =>
      columnsByName['stack_trace']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get exception =>
      columnsByName['exception']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_start_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'level',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tag',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'message',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stack_trace',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'exception',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get coverId =>
      columnsByName['cover_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get size =>
      columnsByName['size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fileFullyWritten =>
      columnsByName['file_fully_written']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get downloadTime =>
      columnsByName['download_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get validTill =>
      columnsByName['valid_till']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fileSizeKB =>
      columnsByName['file_size_k_b']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_89(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_90(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_fully_written',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (file_fully_written IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'download_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'valid_till',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_93(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'file_size_k_b',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
  ),
);
