name: audioplayers_windows
publish_to: "none"
version: 0.0.0

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: AudioplayersPluginWindows

dependencies:
  audioplayers_platform_interface: ^7.1.1
  flutter:
    sdk: flutter

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"
