name: flutter_secure_storage_darwin
description: Custom macOS implementation of flutter_secure_storage using /usr/bin/security.
repository: https://github.com/juho05/crossonic
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface: ^2.0.0
  web: ">=0.5.0 <2.0.0"

flutter:
  plugin:
    implements: flutter_secure_storage
    platforms:
      macos:
        dartPluginClass: FlutterSecureStorageMacOS
      ios:
        pluginClass: FlutterSecureStorageDarwinPlugin
        sharedDarwinSource: true
