name: flutter_secure_storage_linux
description: Stub implementation of flutter_secure_storage.
version: 0.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: FlutterSecureStorageStub
        fileName: flutter_secure_storage_linux.dart