name: Release Draft

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.3"
  APK_BUILD_DIR: "/tmp/build"

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(sed -n 's/^version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p' pubspec.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build_apk:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to env.APK_BUILD_DIR
        run: |
          mkdir -p $APK_BUILD_DIR
          cp -r . $APK_BUILD_DIR

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Dependencies
        working-directory: ${{ env.APK_BUILD_DIR }}
        run: flutter pub get

      - name: Build generated files
        working-directory: ${{ env.APK_BUILD_DIR }}
        run: flutter pub run build_runner build

      - name: Build APK
        working-directory: ${{ env.APK_BUILD_DIR }}
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-result
          path: |
            ${{ env.APK_BUILD_DIR }}/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            ${{ env.APK_BUILD_DIR }}/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            ${{ env.APK_BUILD_DIR }}/build/app/outputs/flutter-apk/app-x86_64-release.apk

  build_linux_x86_64:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get remove libunwind-*
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good gstreamer1.0-plugins-bad libsecret-1-dev libjsoncpp-dev libayatana-appindicator3-dev

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Dependencies
        working-directory: .
        run: flutter pub get
      - name: Build generated files
        working-directory: .
        run: flutter pub run build_runner build
      - name: Compile linux
        working-directory: .
        run: flutter build linux --release

      # tar.gz
      - name: Create tar.gz archive
        run: |
          cd build/linux/x64/release/bundle
          tar -czvf ../../../../../result.tar.gz *

      - name: Upload tar.gz archive
        uses: actions/upload-artifact@v4
        with:
          name: tar-gz-x86-64-result
          path: ./*.tar.gz

      # AppImage
      - name: Copy compiled linux files
        run: |
          mkdir AppDir
          cp -r build/linux/x64/release/bundle/* AppDir/

      - name: Copy logo to AppDir
        run: |
          mkdir -p AppDir/usr/share/icons/hicolor/32x32/apps
          cp assets/icon/desktop/crossonic-32.png AppDir/usr/share/icons/hicolor/32x32/apps/crossonic.png
          mkdir -p AppDir/usr/share/icons/hicolor/128x128/apps
          cp assets/icon/desktop/crossonic-128.png AppDir/usr/share/icons/hicolor/128x128/apps/crossonic.png
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          cp assets/icon/desktop/crossonic-256.png AppDir/usr/share/icons/hicolor/256x256/apps/crossonic.png

      - name: Copy Recipe to correct location
        run: cp scripts/appimage/AppImageBuilder_x86_64.yml AppImageBuilder.yml

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@57c3bc6963f870ce3be103117de5b5e33ffbaeb6
        with:
          recipe: ./AppImageBuilder.yml

      - name: Upload AppImage file
        uses: actions/upload-artifact@v4
        with:
          name: appimage-x86-64-result
          path: ./*.AppImage

  build_windows_x86_64:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GStreamer
        uses: marcpabst/setup-gstreamer@3bafa9efb10f967158fceb6b5b34c2fc4399d141 # v1.5.3
        with:
          version: "1.26.1"
          arch: "x86_64"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Dependencies
        working-directory: .
        run: flutter pub get
      - name: Build generated files
        working-directory: .
        run: flutter pub run build_runner build
      - name: Compile for Windows
        working-directory: .
        run: flutter build windows --release

      - name: Add DLL files
        working-directory: .
        run: |
          Copy-Item scripts/windows/x64/msvcp140.dll build/windows/x64/runner/Release/
          Copy-Item scripts/windows/x64/vcruntime140.dll build/windows/x64/runner/Release/
          Copy-Item scripts/windows/x64/vcruntime140_1.dll build/windows/x64/runner/Release/

      - name: Zip compiled files
        working-directory: .
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath Crossonic.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip-x86-64-result
          path: Crossonic.zip

  release:
    needs:
      - build
      - build_apk
      - build_linux_x86_64
      - build_windows_x86_64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ needs.build.outputs.version }}
          name: v${{ needs.build.outputs.version }}

      # APK
      - name: Download apk file
        uses: actions/download-artifact@v4
        with:
          name: apk-result
          path: apk-result

      - name: Copy apk file to root
        run: cp apk-result/*.apk .

      - name: Upload Release Asset (arm32v7)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: app-armeabi-v7a-release.apk
          asset_name: Crossonic-${{ needs.build.outputs.version }}-android-arm32v7.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset (arm64v8)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: app-arm64-v8a-release.apk
          asset_name: Crossonic-${{ needs.build.outputs.version }}-android-arm64v8.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset (x64)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: app-x86_64-release.apk
          asset_name: Crossonic-${{ needs.build.outputs.version }}-android-x64.apk
          asset_content_type: application/vnd.android.package-archive

      # TAR.GZ (x86_64)
      - name: Download tar.gz file
        uses: actions/download-artifact@v4
        with:
          name: tar-gz-x86-64-result
          path: tar-gz-x86-64-result

      - name: List files in tar.gz-directory
        run: ls -l tar-gz-x86-64-result

      - name: Copy tar.gz file to root
        run: cp tar-gz-x86-64-result/* result.tar.gz

      - name: Upload Release Asset (tar.gz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: result.tar.gz
          asset_name: Crossonic-${{ needs.build.outputs.version }}-linux-x86-64.tar.gz
          asset_content_type: application/gzip

      # APPIMAGE (x86_64)
      - name: Download AppImage file
        uses: actions/download-artifact@v4
        with:
          name: appimage-x86-64-result
          path: appimage-x86-64-result

      - name: List files in appimage-directory
        run: ls -l appimage-x86-64-result

      - name: Copy AppImage file to root
        run: |
          for file in appimage-x86-64-result/*; do
            if [[ $file == *.AppImage && $file != *.AppImage.zsync ]]; then
              cp "$file" result.AppImage
            fi
          done

      - name: Upload Release Asset (AppImage)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: result.AppImage
          asset_name: Crossonic-${{ needs.build.outputs.version }}-linux-x86-64.AppImage
          asset_content_type: application/x-appimage

      # WINDOWS ZIP (x86_64)
      - name: Download windows zip file
        uses: actions/download-artifact@v4
        with:
          name: windows-zip-x86-64-result
          path: windows-zip-x86-64-result

      - name: Copy zip file to root
        run: cp windows-zip-x86-64-result/*.zip result.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: result.zip
          asset_name: Crossonic-${{ needs.build.outputs.version }}-windows-x86-64.zip
          asset_content_type: application/zip
